- name: Ajouter une règle de pare-feu sur FortiGate
  hosts: fortigate
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no

  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Ajouter une règle de pare-feu HTTP/HTTPS
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy:
          policyid: 1
          name: "Autoriser HTTP et HTTPS"
          srcintf: 
            - name: "port2"
          dstintf: 
            - name: "port3"
          srcaddr: 
            - name: "all"
          dstaddr: 
            - name: "all"
          action: "accept"
          schedule: "always"
          service: 
            - name: "HTTP"
            - name: "HTTPS"
          nat: "enable"
